import Head from "next/head";
import { Categories, PostCard, PostWidget } from "../components";
import { FeaturedPosts } from "../sections";
import { getPosts } from "../services";

const posts = [
  { title: "React testing", excerpt: "Learn react testing" },

  { title: "React with Tailwind", excerpt: "Learn react with tailwind" },
];

export default function Home({ posts }) {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>CMS Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPosts />

      <main className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post, index) => (
            <PostCard post={post.node} key={index} />
          ))}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const posts = (await getPosts()) || [];

  console.log(posts);
  return {
    props: {
      posts: posts,
    },
  };
};
